var first_name = "juzer";
var last_name = "Shahiwala";
var full_name = first_name.concat(last_name);
console.log(full_name);
var length_of_full_name = full_name.length;
console.log(length_of_full_name);
var replaced_name = full_name.replace("juzer","Fatema");
console.log(replaced_name);
var making_lower_case = full_name.toLowerCase();
console.log(making_lower_case);
var making_upper_case = full_name.toUpperCase();
console.log(making_upper_case);
var square_root = Math.sqrt(16);
console.log(square_root);
var maximum_number = Math.max(15,10);
console.log(maximum_number);
var minimum_number = Math.min(15,10);
console.log(minimum_number);
var power_eg_1 = Math.pow(4,2);
console.log(power_eg_1);